### PR TITLE
Refactor Servers API guide

### PR DESCRIPTION
**Pull request by catlook**
.Close issue #171

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-5777f3a3cf/docs/cloud-servers/v2/developer-guide/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-010cc40bb5/docs/cloud-servers/v2/developer-guide/)

**Comment by catlook** [comment]
QE is complete:

Now, on to final step pre-publish:
## Update the content URL for refactored API documentation

- [ ] Fork and clone the  [nexus-control](https://github.com/rackerlabs/nexus-control) to your local system.
- [ ] Remove ``developer-guide`` from the deploy URL
      - [ ] Update the deploy URL in the [nexus-control configuration file](https://github.com/rackerlabs/nexus-control/blob/master/config/content.d/developer.rackspace.com.json) as shown in the following example:
       
           **Original:** ``"/docs/cloud-load-balancers/v1/": "https://github.com/rackerlabs/docs-cloud-load-balancers/v1/developer-guide",``

           **Updated:**``"/docs/cloud-load-balancers/v1/": "https://github.com/rackerlabs/docs-cloud-load-balancers/v1/",

- [ ] Update the deploy URL in the [route configuration file](https://github.com/rackerlabs/nexus-control/blob/master/config/routes.d/developer.rackspace.com.json) to match the one in the nexus-control configuration file.
- [ ] Create a redirect rule for the original URL.
      
      - [ ] Edit the [rewrites file](https://github.com/rackerlabs/nexus-control/tree/master/config/rewrites.d) to add a redirect rule for the original URL as shown in the following example:

       ```
          {
             "description": "Redirect load balancers developer-guide URL",
             "from": "^\\/docs\\/cloud-load-balancers\\/v1\\/developer-guide\\/(.*?)",
             "to": "/docs/cloud-load-balancers/v1/$1",
             "rewrite": false,
             "status": 301
         },
      ```
      - [ ] Use a json linter to verify that the JSON syntax is correct.

- [ ] Commit the changes, and push to your fork.
- [ ] Submit the PR for review. 
- [ ] After the PR is merged, verify that the content is deployed to the new URL. 
- [ ] Verify that the redirect rule is working by clicking the Developer Guide link on the [DRC docs landing page](https://developer.rackspace.com/docs/).

**Note:** Nexus-control changes take longer to deploy than content changes. You can check the [nexus-control version information](https://developer.rackspace.com/version/) to determine whether the commit has been deployed. 

## Update the [documentation landing page](https://github.com/rackerlabs/docs-quickstart/edit/master/index.rst)
Update the menu so that it matches the Load Balancers v1 example shown in the following figure: 
load-balancer-v1-doc-menu

**Important:** Don't commit the landing page updates until you have verified that the content has been deployed to the new URL.

Some menus might be slightly different if the product doesn't have an SDK Quickstart, or if it has additional documentation.  If you have questions about the menu content or order, open an [issue](https://github.com/rackerlabs/docs-common/issues/new). 
- [ ] Fork and clone the [docs-quickstart repo](https://github.com/rackerlabs/docs-quickstart) to your local system.
- [ ] Find the menu for the API documentation you are updating.
- [ ] Update the title list and href link targets with the information for your documentation.
- [ ] Save the file. 
- [ ] Submit a PR with the update.
      - [ ] Check the PR builder preview to make sure the landing page renders correctly with your updates.
      - [ ] Request someone to review and merge the PR.

**Comment by catlook** [comment]
QE is done.

On to nexus piece:

## Update the content URL for refactored API documentation

- [ ] Fork and clone the  [nexus-control](https://github.com/rackerlabs/nexus-control) to your local system.
- [ ] Remove ``developer-guide`` from the deploy URL
      - [ ] Update the deploy URL in the [nexus-control configuration file](https://github.com/rackerlabs/nexus-control/blob/master/config/content.d/developer.rackspace.com.json) as shown in the following example:
       
           **Original:** ``"/docs/cloud-load-balancers/v1/": "https://github.com/rackerlabs/docs-cloud-load-balancers/v1/developer-guide",``

           **Updated:**``"/docs/cloud-load-balancers/v1/": "https://github.com/rackerlabs/docs-cloud-load-balancers/v1/",

- [ ] Update the deploy URL in the [route configuration file](https://github.com/rackerlabs/nexus-control/blob/master/config/routes.d/developer.rackspace.com.json) to match the one in the nexus-control configuration file.
- [ ] Create a redirect rule for the original URL.
      
      - [ ] Edit the [rewrites file](https://github.com/rackerlabs/nexus-control/tree/master/config/rewrites.d) to add a redirect rule for the original URL as shown in the following example:

       ```
          {
             "description": "Redirect load balancers developer-guide URL",
             "from": "^\\/docs\\/cloud-load-balancers\\/v1\\/developer-guide\\/(.*?)",
             "to": "/docs/cloud-load-balancers/v1/$1",
             "rewrite": false,
             "status": 301
         },
      ```
      - [ ] Use a json linter to verify that the JSON syntax is correct.

- [ ] Commit the changes, and push to your fork.
- [ ] Submit the PR for review. 
- [ ] After the PR is merged, verify that the content is deployed to the new URL. 
- [ ] Verify that the redirect rule is working by clicking the Developer Guide link on the [DRC docs landing page](https://developer.rackspace.com/docs/).

**Note:** Nexus-control changes take longer to deploy than content changes. You can check the [nexus-control version information](https://developer.rackspace.com/version/) to determine whether the commit has been deployed. 

## Update the [documentation landing page](https://github.com/rackerlabs/docs-quickstart/edit/master/index.rst)
Update the menu so that it matches the Load Balancers v1 example shown in the following figure: 
load-balancer-v1-doc-menu

**Important:** Don't commit the landing page updates until you have verified that the content has been deployed to the new URL.

Some menus might be slightly different if the product doesn't have an SDK Quickstart, or if it has additional documentation.  If you have questions about the menu content or order, open an [issue](https://github.com/rackerlabs/docs-common/issues/new). 
- [ ] Fork and clone the [docs-quickstart repo](https://github.com/rackerlabs/docs-quickstart) to your local system.
- [ ] Find the menu for the API documentation you are updating.
- [ ] Update the title list and href link targets with the information for your documentation.
- [ ] Save the file. 
- [ ] Submit a PR with the update.
      - [ ] Check the PR builder preview to make sure the landing page renders correctly with your updates.
      - [ ] Request someone to review and merge the PR.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-d792dbb94d/docs/cloud-servers/v2/developer-guide/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-f2a302a9c6/docs/cloud-servers/v2/)

**Comment by catlook** [comment]
linked with https://github.com/rackerlabs/nexus-control/pull/528 and https://github.com/rackerlabs/docs-quickstart/pull/106

**Pull request merged**
