### PR TITLE
fix get console per issue #197

### PR DESCRIPTION
**Pull request by catlook**
**Quality audit reminder**

Doc team: While logged in using your O365 account, complete the quality checklist at http://bit.ly/2hwvBKX. Use the checklist for significant doc changes or additions submitted by you or a non-doc staff contributor.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-efb8cdbd5b/docs/cloud-servers/v2/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-7a4772b807/docs/cloud-servers/v2/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-2d03c6139b/docs/cloud-servers/v2/).

**Comment by catlook** [comment]
Brian King (original reporter or issue has approved).

**Comment by catlook** [comment]
closes #197

**Pull request merged**
